### ISSUE TITLE
error: initializer element is not constant (gcc 7.5.0 on SLES 15 SP5)

### ISSUE THREAD

**Issue by ajorg** [google/neper#67]
Trying to compile neper on SLES 15 SP5, I get the following error, introduced by 8b2f9e1ee2814926daa37b470255ebaeba60c897

```
histo.c:31:36: error: initializer element is not constant
 static const double TICKS_TO_SEC = 1.0 / TIME_RESOLUTION;
                                    ^~~
make: *** [<builtin>: histo.o] Error 1
```

gcc is version 7.5.0

`make CC=clang` works, so I have a workaround.
